# Generated by Django 4.1.3 on 2022-12-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'Client')], default=2, verbose_name='Тип Пользователя'),
        ),
    ]
