# Generated by Django 4.1.3 on 2022-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('extended_description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('lessons', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
