# Generated by Django 4.1.3 on 2022-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_blog_traffic_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='extended_description',
            field=models.TextField(null=True),
        ),
    ]
