# Generated by Django 4.1.3 on 2022-12-12 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_advantages_frequently_asked_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_review',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_objects', to='mainpage.instructor'),
        ),
    ]
