# Generated by Django 4.1.3 on 2022-12-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_instructor_review_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor_review',
            name='rating_choices',
            field=models.PositiveSmallIntegerField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Normal'), ('2', 'Bad'), ('1', 'Terrible')], null=True),
        ),
    ]
