# Generated by Django 4.1.3 on 2022-12-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_instructor_review_rating_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_review',
            name='rating_choices',
            field=models.CharField(choices=[('5', 'Excellent'), ('4', 'Good'), ('3', 'Normal'), ('2', 'Bad'), ('1', 'Terrible')], max_length=25, null=True),
        ),
    ]
