# Generated by Django 4.1.3 on 2022-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_remove_instructor_review_post_instructor_review_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_review',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post', to='mainpage.instructor'),
        ),
    ]
