# Generated by Django 4.1.3 on 2022-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_instructor_review_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor_review',
            options={},
        ),
        migrations.RemoveField(
            model_name='instructor_review',
            name='post',
        ),
        migrations.AddField(
            model_name='instructor',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='post', to='mainpage.instructor_review'),
        ),
    ]
