# Generated by Django 4.1.3 on 2022-12-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_instructor_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='category_letter',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='practice',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
