# Generated by Django 4.1.3 on 2022-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_course_age_course_category_letter_course_practice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='favorite_auto',
            new_name='driving_car',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='work_experience',
            new_name='general_experience',
        ),
        migrations.AddField(
            model_name='blog',
            name='extended_description_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='teaching_category',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='teaching_experience',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
