from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage_all, name='home'),
    path('admin_panel', views.admin_panel_all, name='admin'),
    path('<int:id>/instructor', views.InstructorsDetailView.as_view(), name='instructor_info'),
    path('<int:id>/course', views.CoursesDetailView.as_view(), name='course_info'),
    path('<int:id>/blog', views.blogs_extended_info, name='blog'),
    path('<int:id>/traffic_law', views.traffic_laws_extended_info, name='traffic_law'),
    path('instructor/create', views.InstructorCreateView.as_view(), name='instructor_create'),
    path('instructor/<int:id>/update', views.InstructorUpdateView.as_view(), name='instructor_update'),
    path('instructor/<int:id>/delete', views.InstructorDeleteView.as_view(), name='instructor_delete'),
    path('course/create', views.CourseCreateView.as_view(), name='course_create'),
    path('course/<int:id>/update', views.CourseUpdateView.as_view(), name='course_update'),
    path('course/<int:id>/delete', views.CourseDeleteView.as_view(), name='course_delete'),
    path('blog/create', views.BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:id>/update', views.BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:id>/delete', views.BlogDeleteView.as_view(), name='blog_delete'),
    path('traffic_law/create', views.Traffic_LawCreateView.as_view(), name='traffic_law_create'),
    path('traffic_law/<int:id>/update', views.Traffic_LawUpdateView.as_view(), name='traffic_law_update'),
    path('traffic_law/<int:id>/delete', views.Traffic_LawDeleteView.as_view(), name='traffic_law_delete'),
    path('frequently_asked_questions/create', views.Frequently_Asked_QuestionsCreateView.as_view(), name='frequently_asked_questions_create'),
    path('frequently_asked_questions/<int:id>/update', views.Frequently_Asked_QuestionsUpdateView.as_view(), name='frequently_asked_questions_update'),
    path('frequently_asked_questions/<int:id>/delete', views.Frequently_Asked_QuestionsDeleteView.as_view(), name='frequently_asked_questions_delete'),
    path('advantages/create', views.AdvantagesCreateView.as_view(), name='advantages_create'),
    path('advantages/<int:id>/update', views.AdvantagesUpdateView.as_view(), name='advantages_update'),
    path('advantages/<int:id>/delete', views.AdvantagesDeleteView.as_view(), name='advantages_delete'),
    path('instructor_review/create', views.Instructor_ReviewCreateView.as_view(), name='instructor_review_create'),
    path('instructor_review/<int:id>/update', views.Instructor_ReviewUpdateView.as_view(), name='instructor_review_update'),
    path('instructor_review/<int:id>/delete', views.Instructor_ReviewDeleteView.as_view(), name='instructor_review_delete'),
    path('about_us/', views.about_us_view, name='about_us'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('courses/', views.CoursesView.as_view(), name='courses'),
    path('courses/<int:id>/courses_info', views.CoursesDetailView.as_view(), name='courses_info'),
    path('instructors/', views.InstructorsView.as_view(), name='instructors'),
    path('instructors/<int:id>/instructors_info', views.InstructorsDetailView.as_view(), name='instructors_info'),
    path('frequently_asked_questions/', views.FAQView.as_view(), name='frequently_asked_questions'),
]
